name: fredjaya-rec-bench-0.1.0
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  # S1_filter_fasta
  - python=3.7.3
  - matplotlib=3.1.0
  # S4_santa-sim
  - java-jdk=8.0.92
  # Pipeline tracing and reporting
  #- graphviz=2.40.1 # Nextflow still outputs 'install graphviz' error
