---
title: "Detection condition proportions"
author: "Fred Jaya"
output: 
  html_document:
    theme: spacelab
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = T,
  warning = F,
  fig.width = 8,
  fig.path = "/home/frederickjaya/GitHub/rec-bench/figs/")

library(dplyr)
library(tidyr)
library(ggplot2)
library(viridis)
library(cowplot)
library(scales)

theme_fj <- theme_minimal() +
  theme(panel.grid = element_blank(), 
        axis.title = element_text(size = 10),
        legend.text = element_text(size = 10),
        legend.title = element_text(size = 10))

# Set colour pallete
pal <- c(TP = '#054A91', FP = '#6BA3DB', TN = '#BB342F', FN = '#DE6C68', Failed = '#F0F0F0')
```

## Data prep  

```{r phi_table}
phi <- 
  read.csv("~/Dropbox/Masters/02_working/2105_pub/F1_profile_conditions.csv") %>%
  mutate(condition = factor(condition, levels = c("TP", "FP", "TN", "FN"))) %>%
  mutate(rec = scientific(rec))

# Frequency of each condition, per sequence
table(phi$condition)
```

```{r 3seq_table}
# Read in condition data from rec-bench --class
tseq <-
  read.csv("~/Dropbox/Masters/02_working/2105_pub/F2_3seq_conditions.csv") %>%
  mutate(RC_seq = if_else(RC_seq == "nan", "Failed", RC_seq)) %>%
  mutate(RC_seq = factor(RC_seq, levels = c("TP", "FP", "TN", "FN", "Failed")))
    
# Frequency of each condition per sequence
table(tseq$RC_seq, useNA = "ifany") 
```

```{r}
# Create table of all parameter combinations, per-sequence n = 42000
# As GENECONV and UCHIME do not have complete records

# Unique simulation parameter values
mut <- c(0, 1e-05, 1e-04, 1e-03, 1e-02, 1e-01, 1)
rec <- c(0e+00, 1e-03, 5e-03, 1e-02, 5e-02, 1e-01)
dualInf <- c(0, 1)
rep <- 1:5
seq_name <- paste("seq", 1:100, sep = "_")

# Make df
params <- crossing(mut, rec, dualInf, rep, seq_name)
rm(mut, rec, dualInf, rep, seq_name)
```

```{r uchime_table}
# From `sim_stats.Rmd` read in simulated breakpoint file to identify conditions
# for UCHIME run. Possible as UCHIME detected no recombination == either TN/FN
bp_counts <- 
  read.csv("~/Dropbox/Masters/02_working/2105_pub/V5_bp_stats.csv", header = T) %>%
  select(mut, rec, dualInf, rep, seq_name = seq) %>%
  # All sequences with simulated recombination == FN
  mutate(RC_seq = as.factor("FN"))

# Merge with the rest of simulated sequences with no breakpoints (TN)
uchime <- 
  params %>%
  left_join(bp_counts, by = c("mut", "rec", "dualInf", "rep", "seq_name")) %>%
  mutate(RC_seq = if_else(is.na(RC_seq), "TN", "FN"))


#write.csv(uchime, "~/Dropbox/Masters/02_working/2105_pub/F4_uchime.csv", row.names = F)

table(uchime$RC_seq, useNA = 'ifany')
```

```{r gc_table, eval=F}
# Read gc conditions
gc <- 
  read.csv("~/Dropbox/Masters/02_working/2105_pub/F3_geneconv_conditions.csv")

# Read in traces to identify GENECONV runs that were not successful (too few polymorphisms)
gc_trace <-
  read.csv("~/Dropbox/Masters/02_working/2105_pub/tracing/trace.csv") %>%
  filter(status == "FAILED") %>%
  # Separate method and parameters into individual columns
  separate(col = name, into = c('name', 'params'), sep = ' \\(')

# Clean parameters for plotting
gc_trace$params <- gsub('[a-z]', '', gc_trace$params)
gc_trace$params <- gsub('^_'   , '', gc_trace$params)
gc_trace$params <- gsub('\\.\\)'   , '', gc_trace$params)

# Separate parameters into individual columns
gc_trace <- 
  gc_trace %>%
  separate(col = params, into = c('mut', 'rec', 'seqn', 'dualInf', 'rep'), 
           sep = '_', remove = T) %>%
  select(c('mut', 'rec', 'seqn', 'dualInf', 'rep')) %>%
  # IDGAF
  mutate(mut = as.numeric(mut),
         rec = as.numeric(rec),
         seqn = as.integer(seqn),
         dualInf = as.integer(dualInf),
         rep = as.numeric(rep))

# Get non-fails
pass <- 
  gc %>%
  anti_join(gc_trace, by = c('mut', 'rec', 'rep'))

# Get fails
fail <- 
  gc_trace %>%
  left_join(gc, by = c('mut', 'rec', 'rep', 'seqn', 'dualInf'))

# Replace conditions with NAs
fail[7:ncol(fail)] <- NA

# Merge all traces
gc_merged <- rbind(pass, fail)

# combine with the rest of the simulated sequences where GENECONV did not
# detect any recombination. GENECONV only outputs positive results.
gc_merged2 <- 
  params %>%
  left_join(gc_merged %>% select(mut:RC_seq)) %>%
  mutate(RC_seq = if_else(mut == 0, "Failed", RC_seq)) %>%
  mutate(RC_seq = if_else(is.na(RC_seq), "TN", RC_seq))

rm(gc, gc_trace, pass)
table(gc_merged2$RC_seq, useNA = 'ifany')


#write.csv(gc_merged2, "~/Dropbox/Masters/02_working/2105_pub/F3_geneconv_conditions_allseqs.csv", row.names = F)
```

`sim_bp$bps` contains the positions of all simulated breakpoints per sequence. As we are comparing the conditions on the sequence level, convert this column to P/A of recombination. `sim_bp$bps == ""`  indicate no recombination was simulated (similar to `params`).  

```{r}
sim_bp <- read.csv("~/Dropbox/Masters/02_working/2105_pub/V2_santa_bp.csv")

sim_bp <- 
  sim_bp %>%
  mutate(bps = if_else(bps == "", F, T)) %>%
  rename(simulated = bps)

table(sim_bp$simulated)
```

```{r gc_table2}
# This includes both paired and unpaired runs
gc <- 
  read.csv("~/Dropbox/Masters/02_working/2105_pub/F3_geneconv_summarised.csv") %>%
  # Wrangle file name/paths into separate parameters
  mutate(file = gsub("(/shared/homes/13444841/2104_performance/B3_geneconv/msa_)|(.tab)", "", file)) %>%
  mutate(file = gsub("[a-zA-Z]", "", file)) %>%
  separate(col = file, into = c('mut', 'rec', 'seqnum', 'dualInf', 'rep'), sep = "_") %>%
  select(mut, rec, seqnum, dualInf, rep, seq_names) %>%
  # Next, sequence == 1 row
  separate(col = seq_names, into = c("seq_1", "seq_2"), sep = ";") %>%
  pivot_longer(cols = seq_1:seq_2, values_to = "seq_name") %>%
  mutate(seq = gsub(":.+", "", seq_name)) %>%
  select(-name, -seq_name) %>%
  # Drop duplicates
  distinct() %>%
  # Add observation
  mutate(geneconv = T) %>%
  # Change class
  mutate(across(mut:rep, as.numeric))

# Next, add to whole list of simulated sequences and calculate conditions for each
gc2 <- 
  sim_bp %>%
  left_join(gc) %>%
  # Fill in GENECONV with no detections
  mutate(geneconv = if_else(is.na(geneconv), F, T)) %>%
  # Calculate condition per sequence
   mutate(Condition = 
           if_else(simulated == T & geneconv == T, "TP",
                   if_else(simulated == F & geneconv == T, "FP",
                           if_else(simulated == T & geneconv == F, "FN", "TN")))) %>%
  mutate(Method = "GENECONV") %>%
  # As none ran on m=0
  mutate(Condition = if_else(mut == 0, "Failed", Condition))

#write.csv(gc2, "geneconv_conditions_2023.csv")
```


```{r openrdp_prep}
sim_bp <- 
  read.csv("~/Dropbox/Masters/02_working/2307_conditions/sim_bp.txt", header =F, sep = " ") %>%
  mutate(file = gsub(".fasta", "", V1)) %>%
  select(file, seq_name = V2) %>%
  mutate(simulated = if_else(grepl(':', seq_name), T, F))

openrdp_conditions <- function(path, method) {
  read.csv(path, header = F, sep = " ") %>%
    select(file = V1, seq_name = V2) %>%
    mutate(detected = T) %>%
    right_join(sim_bp, by = c('file', 'seq_name')) %>%
    replace_na(list(detected = F)) %>%
    mutate(
      RC_seq = if_else(simulated == T & detected == T, "TP",
                       if_else(simulated == T & detected == F, "FN",
                               if_else(simulated == F & detected == T, "FP",
                                       if_else(simulated == F & detected == F, "TN", "ERROR"))))) %>%
    mutate(Method = method) %>%
    mutate(file = gsub('[a-z]', '', file)) %>%
    mutate(file = gsub('^_', '', file)) %>%
    separate(col = file, into = c('mut', 'rec', 'seqn', 'dualInf', 'rep'), sep = '_', remove = T) %>%
    mutate(mut = as.numeric(mut),
           rec = as.numeric(rec),
           seqn = as.integer(seqn),
           dualInf = as.integer(dualInf),
           rep = as.numeric(rep))
    
    
}

rdp <- openrdp_conditions("~/Dropbox/Masters/02_working/2307_conditions/rdp.pos", "rdp")
chimaera <- openrdp_conditions("~/Dropbox/Masters/02_working/2307_conditions/chimaera.pos", "chimaera")
maxchi <- openrdp_conditions("~/Dropbox/Masters/02_working/2307_conditions/maxchi.pos", "chimaera")

#write.csv(rdp, "~/Dropbox/Masters/02_working/2307_conditions/rdp.csv", row.names = F, quote = F)
#write.csv(chimaera, "~/Dropbox/Masters/02_working/2307_conditions/chimaera.csv", row.names = F, quote = F)
```

## Plot prep  

```{r phi_pies, fig.height=5.2, fig.width=5}
phi_pies <- 
  phi %>%
  mutate(mut = factor(mut, levels = c(1, 0.1, 0.01, 0.001, 1e-04, 1e-05, 0))) %>%
  mutate(rec = factor(rec, levels = c('0e+00', '1e-03', '5e-03', '1e-02', '5e-02', '1e-01'))) %>%
  filter(mut != 1) %>%
  ggplot(aes(x = factor(1), fill = condition)) +
  theme_fj +
  geom_bar(stat = 'count') +
  facet_grid(cols = vars(rec), rows = vars(mut), switch = 'both') +
  coord_polar(theta = 'y') +
  scale_fill_manual(na.value = "#F0F0F0", values = pal) +
  theme(axis.text = element_blank(),
        legend.position = 'bottom',
        axis.title.x = element_blank(),
        strip.text.y.left = element_text(angle = 0),
        plot.tag.position = c(0.57, 0.09),
        plot.tag = element_text(size = 10),
        plot.margin = unit(c(5.5, 20, 5.5, 5.5), 'pt')) +
  labs(x = "Mutation rate", 
       fill = "Per-window conditions",
       tag = "Recombination rate")

plot_grid(phi_pies, labels = "PhiPack (Profile)", label_size = 10)
rm(phi, phi_pies)
```

```{r 3seq_pie, fig.height=6, fig.width=5}
tseq_pies <- 
  tseq %>%
  mutate(mut = factor(mut, levels = c(1, 0.1, 0.01, 0.001, 1e-04, 1e-05, 0))) %>%
  mutate(rec = factor(rec, levels = c(0e+00, 1e-03, 5e-03, 1e-02, 5e-02, 1e-01))) %>%
  filter(mut != 1) %>%
  ggplot(aes(x = factor(1), fill = RC_seq)) +
  theme_fj +
  geom_bar(stat = 'count') +
  facet_grid(cols = vars(rec), rows = vars(mut), switch = 'both') +
  coord_polar(theta = 'y') +
  scale_fill_manual(values = pal) +
  theme(axis.text = element_blank(),
        legend.position = 'right',
        axis.title.x = element_blank(),
        strip.text.y.left = element_text(angle = 0),
        plot.tag.position = c(0.57, 0),
        plot.tag = element_text(size = 10),
        plot.margin = unit(c(5.5, 20, 5.5, 5.5), 'pt')) +
  guides(fill = guide_legend(title.position = "top")) +
  labs(x = "Mutation rate", 
       fill = "Per-sequence\nconditions",
       tag = "Recombination rate")
```

```{r gc_pie, fig.height=6, fig.width=5}
gc_pies <- 
  gc2 %>%
  mutate(mut = factor(mut, levels = c(1, 0.1, 0.01, 0.001, 1e-04, 1e-05, 0))) %>%
  mutate(rec = factor(rec, levels = c(0, 1e-03, 5e-03, 1e-02, 5e-02, 1e-01))) %>%
  filter(mut != 1) %>%
  ggplot(aes(x = factor(1), fill = Condition)) +
  theme_fj +
  geom_bar(stat = 'count') +
  facet_grid(cols = vars(rec), rows = vars(mut), switch = 'both') +
  coord_polar(theta = 'y') +
  scale_fill_manual(values = pal) +
  theme(axis.text = element_blank(),
        legend.position = 'bottom',
        axis.title.x = element_blank(),
        strip.text.y.left = element_text(angle = 0),
        plot.tag.position = c(0.57, 0),
        plot.tag = element_text(size = 10),
        plot.margin = unit(c(5.5, 20, 5.5, 5.5), 'pt')) +
  labs(x = "Mutation rate", 
       fill = "Per-sequence conditions",
       tag = "Recombination rate")
```

```{r uc_pie, fig.height=6, fig.width=5}
uc_pies <- 
  uchime %>%
  mutate(mut = factor(mut, levels = c(1, 0.1, 0.01, 0.001, 1e-04, 1e-05, 0))) %>%
  filter(mut != 1) %>%
  ggplot(aes(x = factor(1), fill = RC_seq)) +
  theme_fj +
  geom_bar(stat = 'count') +
  facet_grid(cols = vars(rec), rows = vars(mut), switch = 'both') +
  coord_polar(theta = 'y') +
  scale_fill_manual(na.value = "#F0F0F0", values = pal) +
  theme(axis.text = element_blank(),
        legend.position = 'bottom',
        axis.title.x = element_blank(),
        strip.text.y.left = element_text(angle = 0),
        plot.tag.position = c(0.57, 0),
        plot.tag = element_text(size = 10),
        plot.margin = unit(c(5.5, 20, 5.5, 5.5), 'pt')) +
  labs(x = "Mutation rate", 
       fill = "Per-sequence conditions",
       tag = "Recombination rate")
```

```{r rdp_pie, fig.height=6, fig.width=5}
rdp_pies <- 
  rdp %>%
  mutate(mut = factor(mut, levels = c(0.1, 0.01, 0.001, 1e-04, 1e-05, 0))) %>%
  mutate(rec = factor(rec, levels = c(0e+00, 1e-03, 5e-03, 1e-02, 5e-02, 1e-01))) %>%
  ggplot(aes(x = factor(1), fill = RC_seq)) +
  theme_fj +
  geom_bar(stat = 'count') +
  facet_grid(cols = vars(rec), rows = vars(mut), switch = 'both') +
  coord_polar(theta = 'y') +
  scale_fill_manual(values = pal) +
  theme(axis.text = element_blank(),
        legend.position = 'right',
        axis.title.x = element_blank(),
        strip.text.y.left = element_text(angle = 0),
        plot.tag.position = c(0.57, 0),
        plot.tag = element_text(size = 10),
        plot.margin = unit(c(5.5, 20, 5.5, 5.5), 'pt')) +
  guides(fill = guide_legend(title.position = "top")) +
  labs(x = "Mutation rate", 
       fill = "Per-sequence\nconditions",
       tag = "Recombination rate")
```

```{r maxchi_pie, fig.height=6, fig.width=5}
maxchi_pies <- 
  maxchi %>%
  mutate(mut = factor(mut, levels = c(0.1, 0.01, 0.001, 1e-04, 1e-05, 0))) %>%
  mutate(rec = factor(rec, levels = c(0e+00, 1e-03, 5e-03, 1e-02, 5e-02, 1e-01))) %>%
  ggplot(aes(x = factor(1), fill = RC_seq)) +
  theme_fj +
  geom_bar(stat = 'count') +
  facet_grid(cols = vars(rec), rows = vars(mut), switch = 'both') +
  coord_polar(theta = 'y') +
  scale_fill_manual(values = pal) +
  theme(axis.text = element_blank(),
        legend.position = 'right',
        axis.title.x = element_blank(),
        strip.text.y.left = element_text(angle = 0),
        plot.tag.position = c(0.57, 0),
        plot.tag = element_text(size = 10),
        plot.margin = unit(c(5.5, 20, 5.5, 5.5), 'pt')) +
  guides(fill = guide_legend(title.position = "top")) +
  labs(x = "Mutation rate", 
       fill = "Per-sequence\nconditions",
       tag = "Recombination rate")
```

```{r chimaera_pie, fig.height=6, fig.width=5}
chimaera_pies <- 
  chimaera %>%
  mutate(mut = factor(mut, levels = c(0.1, 0.01, 0.001, 1e-04, 1e-05, 0))) %>%
  mutate(rec = factor(rec, levels = c(0e+00, 1e-03, 5e-03, 1e-02, 5e-02, 1e-01))) %>%
  ggplot(aes(x = factor(1), fill = RC_seq)) +
  theme_fj +
  geom_bar(stat = 'count') +
  facet_grid(cols = vars(rec), rows = vars(mut), switch = 'both') +
  coord_polar(theta = 'y') +
  scale_fill_manual(values = pal) +
  theme(axis.text = element_blank(),
        legend.position = 'right',
        axis.title.x = element_blank(),
        strip.text.y.left = element_text(angle = 0),
        plot.tag.position = c(0.57, 0),
        plot.tag = element_text(size = 10),
        plot.margin = unit(c(5.5, 20, 5.5, 5.5), 'pt')) +
  guides(fill = guide_legend(title.position = "top")) +
  labs(x = "Mutation rate", 
       fill = "Per-sequence\nconditions",
       tag = "Recombination rate")
```

```{r main_pies, fig.width=10, fig.height=12}
leg <- plot_grid(get_legend(tseq_pies), NULL, NULL, NULL, rel_widths = c(1, 2), rel_heights = c(1, 2))

plot_grid(tseq_pies + theme(legend.position = 'none'),
          gc_pies + theme(legend.position = 'none'),
          uc_pies + theme(legend.position = 'none'),
          rdp_pies + theme(legend.position = 'none'),
          maxchi_pies + theme(legend.position = 'none'),
          chimaera_pies + theme(legend.position = 'none'),
          get_legend(tseq_pies+ theme(legend.position = "bottom")),
          labels = c("a) 3SEQ", "b) GENECONV", "c) UCHIME (VSEARCH)", "d) RDP (OpenRDP)", "e) MaxChi (OpenRDP)", "e) Chimaera (OpenRDP)"), 
          label_size = 10, ncol = 2)

rm(tseq, uchime, gc_merged, gc_merged2, fail, bp_counts, params)
```

