---
title: "Scalability"
author: "Fred Jaya"
output: 
   html_document:
     theme: spacelab
     code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = T,
  warning = F,
  fig.width = 8,
  fig.path = "/Users/13444841/GitHub/rec-bench/figs/")

library(dplyr)
library(tidyr)
library(ggplot2)
library(viridis)
Sys.setenv(RETICULATE_PYTHON = "/usr/local/bin/python3")
library(reticulate)
library(stringr)

use_condaenv("trace_parse", required = T)

theme_fj <- theme_minimal() +
  theme(panel.grid = element_blank())

rdm_pal <- c("#FC8D62", '#8DA0CB', '#66C2A5',  '#E78AC3', '#FFD92F')
```

```{r read_data}
#n100 <- read.csv("n100.csv")
n1000 <- read.csv("~/Dropbox/Masters/02_working/2105_scale/n1000.csv")
n5000 <- read.csv("~/Dropbox/Masters/02_working/2105_scale/n5000.csv")
n10000 <- read.csv("~/Dropbox/Masters/02_working/2105_scale/n10000.csv")
n50000 <- read.csv("~/Dropbox/Masters/02_working/2105_scale/n50000.csv")

traces <- 
  rbind(n1000, n5000, n10000, n50000) %>%
  select(name, status, exit, duration, realtime, X.cpu, peak_rss, peak_vmem) %>%
  filter(str_detect(name, "santa|sweep|filter", negate = T)) %>%
  separate(col = name, into = c('name', 'params'), sep = ' \\(') %>%
  mutate(params = gsub('[a-z]', '', params)) %>%
  mutate(params = gsub('^__', '', params)) %>%
  mutate(params = gsub('^_', '', params)) %>%
  mutate(params = gsub('\\.)$', '', params)) %>%
  separate(col = params, into = c('mut', 'rc', 'seq_n', 'dual_inf', 'rep'), 
           sep = '_', remove = T) %>%
  mutate(mut = as.numeric(mut), rc = as.numeric(rc), seq_n = as.numeric(seq_n), 
         dual_inf = as.numeric(dual_inf), rep = as.numeric(rep))

rm(n1000, n5000, n10000, n50000)

# Convert duration and realtime to hours
source_python("~/GitHub/rec-bench/bin/convert_time.py")
traces$duration_hours <- sapply(traces$duration, nf_hours) # dplyr::mutate doesn't like this for some reason
traces$realtime_hours <- sapply(traces$realtime, nf_hours)

# Combine UCHIME and UCHIME_DEREP times
uchime <- 
  traces %>%
  filter(name == 'B4_uchime')

derep <- traces %>%
  filter(name == 'B4_uchime_derep')

joined_uchime <- full_join(uchime, derep, 
                  by = c('mut', 'rc', 'seq_n', 'dual_inf', 'rep'))

rm(uchime, derep)

joined_uchime <- 
  joined_uchime %>%
  mutate(name = "B4_uchime_joined", realtime_hours = realtime_hours.x + realtime_hours.y,
         duration_hours = duration_hours.x + duration_hours.y) %>%
  select(name = name.x, mut, rc, seq_n, dual_inf, rep, status = status.x, 
         exit = exit.x, duration = duration.x, realtime = realtime.x, 
         X.cpu = X.cpu.x, peak_rss = peak_rss.x, peak_vmem = peak_vmem.x, 
         duration_hours, realtime_hours)

traces2 <- 
  traces %>%
  filter(name != "B4_uchime") %>%
  filter(name != "B4_uchime_derep") %>%
  bind_rows(joined_uchime)
```

```{r scale_main, fig.width=8, fig.height=5}
traces2 %>%
  mutate(seq_n = gsub('^', 'n = ', seq_n)) %>%
  mutate(seq_n = factor(seq_n, levels = c('n = 1000', 'n = 5000', 'n = 10000', 'n = 50000'))) %>%
  filter(exit == 0) %>%
  mutate(name = gsub('B1_phi_profile', 'PhiPack (Profile)', name)) %>%
  mutate(name = gsub('B2_3seq', '3SEQ', name)) %>%
  mutate(name = gsub('B3_geneconv', 'GENECONV', name)) %>%
  mutate(name = gsub('B4_uchime', 'VSEARCH (UCHIME)', name)) %>%
  mutate(name = gsub('B5_gmos', 'gmos', name)) %>%
  mutate(name = factor(name, levels = c('PhiPack (Profile)', '3SEQ', 'GENECONV', 'VSEARCH (UCHIME)', 'gmos'))) %>%
  ggplot(aes(x = as.factor(mut), y = duration_hours, col = name, group = name)) +
  geom_jitter(alpha = 0.25, shape = 16, size = 1.5) +
  stat_summary(geom = 'line', fun = mean, size = 0.75) +
  stat_summary(geom = 'point', fun = mean, shape = 18, size = 3) +
  facet_wrap(vars(seq_n), nrow = 2) +
  scale_colour_manual(values = rdm_pal) +
  labs(col = "Method",
       x = "Mutation rate",
       y = "CPU hours") +
  scale_y_log10() +
  theme_fj +
  theme(panel.border = element_rect(colour = "darkgrey", fill=NA, size=1)) +
  annotation_logticks(sides = "l", colour = "darkgrey")
```

### Supplementary

```{r scale_rc, fig.width=7, fig.height=4}
traces2 %>%
  mutate(seq_n = gsub('^', 'n = ', seq_n)) %>%
  mutate(seq_n = factor(seq_n, levels = c('n = 1000', 'n = 5000', 'n = 10000', 'n = 50000'))) %>%
  filter(exit == 0) %>%
  mutate(name = gsub('B1_phi_profile', 'PhiPack (Profile)', name)) %>%
  mutate(name = gsub('B2_3seq', '3SEQ', name)) %>%
  mutate(name = gsub('B3_geneconv', 'GENECONV', name)) %>%
  mutate(name = gsub('B4_uchime', 'VSEARCH (UCHIME)', name)) %>%
  mutate(name = gsub('B5_gmos', 'gmos', name)) %>%
  mutate(name = factor(name, levels = c('PhiPack (Profile)', '3SEQ', 'GENECONV', 'VSEARCH (UCHIME)', 'gmos'))) %>%
  ggplot(aes(x = as.factor(rc), y = duration_hours, col = name, group = name)) +
  geom_jitter(alpha = 0.25, shape = 16, size = 1.5) +
  stat_summary(geom = 'line', fun = mean, size = 0.75) +
  stat_summary(geom = 'point', fun = mean, shape = 18, size = 3) +
  facet_wrap(vars(seq_n), nrow = 1) +
  scale_colour_manual(values = rdm_pal) +
  labs(col = "Method",
       x = "Recombination rate",
       y = "CPU hours") +
  scale_y_log10() +
  theme_fj +
  theme(panel.border = element_rect(colour = "darkgrey", fill=NA, size=1),
        legend.position = 'bottom') +
  annotation_logticks(sides = "l", colour = "darkgrey")
```
