---
title: "Simulation Statistics"
author: "Fred Jaya"
output: 
  html_document:
    theme: spacelab
    code_folding: hide
---
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = F,
  warning = F,
  fig.width = 8,
  dev = 'png',
  fig.path = "/home/frederickjaya/GitHub/rec-bench/figs/")

library(dplyr)
library(tidyr)
library(tibble)
library(ggplot2)
library(viridis)
library(scales)
library(cowplot)

theme_fj <- theme_minimal() +
  theme(panel.border = element_rect(fill = NA, color = 'grey'),
        panel.grid = element_blank(), axis.title = element_text(size = 10),
        legend.title = element_text(size = 10))
```

## Data prep  

```{r diversity_prep, echo = F}
sqrt_dist <- 
  read.csv("~/Dropbox/Masters/02_working/2105_pub/V4_sim_distances.csv", header = F) %>%
  rename('file' = V1) %>%
  mutate(file = gsub('.*\\/', '', file)) %>%
  mutate(file = gsub('^msa_', '', file)) %>%
  mutate(file = gsub('\\.fasta$', '', file)) %>%
  mutate(file = gsub('[a-z]', '', file)) %>%
  separate(col = file, sep = '_',
           into = c('mut', 'rec', 'seqn', 'dualInf', 'rep')) %>%
  pivot_longer(cols = V2:V4951) %>%
  select(-name, 'sqrt_pair_dist' = value) %>%
  mutate(mut = as.numeric(mut),
         rec = as.numeric(rec))

dist_medians <- 
  sqrt_dist %>%
  group_by(mut) %>%
  summarise(median = median(sqrt_pair_dist))
```

```{r bp_counts_prep, echo = F}
# Open in excel and save again to add commas
bp_counts <- read.csv("~/Dropbox/Masters/02_working/2105_pub/V5_bp_stats.csv", header = T)

# Sum number of breakpoints per run 
bp_counts <- bp_counts %>%
  mutate(num_bp = 
           rowSums(
             !is.na(
               select(., -c("mut", "rec", "seqnum", "dualInf", "rep", "seq")))))

# Pivot breakpoints into one column
bp_pivot <- bp_counts %>%
  select(-num_bp) %>%
  pivot_longer(cols = 7:ncol(.),
               values_to = 'bp_position', 
               values_drop_na = T) %>%
  select(-name)

# Subset for plotting
num_bp <-
  bp_counts %>%
  select(mut, rec, rep, seq, dualInf, num_bp) %>%
  mutate(rec = scientific(rec)) %>%
  add_row(mut = 0, rec = '0') %>%
  mutate(rec = factor(rec, levels = c('0', '1e-03', '5e-03', '1e-02', '5e-02', '1e-01')))

num_rec <-
  num_bp %>%
  group_by(mut, rec, rep) %>%
  tally() %>%
  # This is so no boxplots are visualised when no recombination occurs
  mutate(n = if_else(rec == "0", as.integer(NA), n))
```

## Plots prep  

```{r diversity_density, fig.width=8, fig.height=2.5}
a <- 
  sqrt_dist %>%
  filter(mut != 1) %>%
  ggplot(aes(sqrt_pair_dist, ..scaled.., col = as.factor(mut), fill = as.factor(mut))) +
  geom_density(alpha = 0.1) +
  geom_vline(data = dist_medians %>% filter(mut != 1), aes(xintercept = median, color = as.factor(mut)), linetype = 'dashed') +
  scale_x_continuous(breaks = seq(0, 1, 0.1)) +
  scale_fill_viridis(discrete = T) +
  scale_color_viridis(discrete = T) +
  theme_fj +
  labs(x = 'Pairwise sequence distance per population', y = 'Density', fill = "Mutation rate", col = "Mutation rate")
```

```{r bp_per_seq, fig.width=3.5, fig.height=3}
b <- 
  num_bp %>%
  filter(mut != 1) %>%
  ggplot(aes(x = as.factor(rec), y = num_bp)) +
  geom_boxplot(position = position_dodge2(preserve = 'single'), alpha = 0.6, shape = 16) +
  theme_fj +
  labs(x = "Recombination rate", y = "Number of breakpoints\nper sequence")
```

```{r rc_per_pop, fig.width=3.5, fig.height=3}
c <- 
  num_rec %>%
  filter(mut != 1) %>%
  ggplot(aes(x = as.factor(rec), y = n)) +
  geom_boxplot(position = position_dodge2(preserve = 'single'), alpha = 0.6, shape = 16) +
  scale_y_continuous(breaks = c(0, 5, 10, 15), limits = c(0, 17)) +
  theme_fj +
  labs(x = "Recombination rate", y = "Number of recombinant\nsequences per population")
```

## Figures  

```{r fig2, fig.height=4.5}
top <- plot_grid(a, labels = 'a)', label_size = 10)
bot <- plot_grid(b, c, nrow = 1, labels = c('b)', 'c)'), label_size = 10)
plot_grid(top, bot, nrow = 2)
```

## Supplementary  
```{r diversity_per_rec, fig.width=8, fig.height=3, eval=F}
sqrt_dist %>%
  ggplot(aes(x = as.factor(mut), y = sqrt_pair_dist, fill = as.factor(rec))) +
  geom_boxplot(position = position_dodge2(preserve = 'single'), alpha = 0.6, shape = 16) +
  theme_fj +
  scale_fill_viridis(discrete = T) +
  labs(x = "Mutation rate", y = "Number of breakpoints\nper sequence", fill = "Recombination rate")
```

```{r bp_per_seq_mut, fig.width=8, fig.height=3, eval=F}
num_bp %>%
  ggplot(aes(x = as.factor(rec), y = num_bp, fill = as.factor(mut))) +
  geom_boxplot(position = position_dodge2(preserve = 'single'), alpha = 0.6, shape = 16) +
  theme_fj +
  scale_fill_viridis(discrete = T) +
  labs(x = "Recombination rate", y = "Pairwise sequence\ndistance per population", fill = "Mutation rate")
```

```{r rc_per_pop_mut, fig.width=8, fig.height=3, eval=F}
ggplot(num_rec, 
       aes(x = as.factor(rec), y = n, fill = as.factor(mut))) +
  geom_boxplot(position = position_dodge2(preserve = 'single'), alpha = 0.6) +
  theme_fj +
  scale_fill_viridis(discrete = T) +
  labs(x = "Recombination rate", y = "Number of recombinant\nsequences per population",
       fill = "Mutation rate")
```

```{r bp_densities, fig.height=8}
bp_densities <- 
  bp_pivot %>%
  bind_rows(data.frame(rec = 0, mut = unique(bp_pivot$mut))) %>%
  filter(mut != 1) %>%
  mutate(mut = factor(levels = c(1e-1, 1e-2, 1e-3, 1e-4, 1e-5, 0), mut)) %>%
  ggplot(aes(bp_position)) +
  geom_density(adjust = 1/2, fill = 'black', alpha = 0.4) +
  theme_fj +
  facet_grid(cols = vars(rec), rows = vars(mut)) + 
  theme(axis.title = element_blank())

plot_grid(bp_densities, scale = 0.95) +
  draw_label("Sequence position", x = 0.5, y = 0.01) +
  draw_label("Breakpoint density", x = 0.015, y = 0.5, angle = 90) +
  draw_label("Recombination rate", x = 0.5, y = 0.99) +
  draw_label("Mutation rate", x = 0.975, y = 0.5, angle = 270)
```

